apiVersion: v1
kind: Namespace
metadata:
  name: shopsphere-stage9
  labels:
    name: shopsphere-stage9
    app.kubernetes.io/name: shopsphere
    app.kubernetes.io/part-of: shopsphere-ecommerce
    stage: "stage-9"
