server:
  port: 8082

spring:
  application:
    name: order-service
  data:
    mongodb:
      host: ${MONGODB_HOST:localhost}
      port: 27017
      database: shopsphere_orders
      username: root
      password: root
      authentication-database: admin
    redis:
      host: ${REDIS_HOST:localhost}
      port: 6379

services:
  product:
    url: ${PRODUCT_SERVICE_URL:http://localhost:8081}
  notification:
    url: ${NOTIFICATION_SERVICE_URL:http://localhost:8087}

springdoc:
  api-docs:
    path: /api-docs
  swagger-ui:
    path: /swagger-ui.html
    operations-sorter: method
