apiVersion: v1
kind: ServiceAccount
metadata:
  name: order-service-sa
  namespace: shopsphere-stage9
  annotations:
    # Injected with the IRSA role ARN from Terraform module.iam.order_service_sqs_role_arn
    eks.amazonaws.com/role-arn: arn:aws:iam::165772574557:role/shopsphere-stage9-order-sqs-role
