apiVersion: elbv2.k8s.aws/v1beta1
kind: TargetGroupBinding
metadata:
  name: frontend-service-tgb
  namespace: shopsphere-stage9
spec:
  serviceRef:
    name: frontend-service
    port: 8080
  targetType: instance
  targetGroupARN: "${STAGE9_FRONTEND_TG_ARN}"
---
apiVersion: elbv2.k8s.aws/v1beta1
kind: TargetGroupBinding
metadata:
  name: product-service-tgb
  namespace: shopsphere-stage9
spec:
  serviceRef:
    name: product-service
    port: 8081
  targetType: instance
  targetGroupARN: "${STAGE9_PRODUCT_TG_ARN}"
---
apiVersion: elbv2.k8s.aws/v1beta1
kind: TargetGroupBinding
metadata:
  name: order-service-tgb
  namespace: shopsphere-stage9
spec:
  serviceRef:
    name: order-service
    port: 8082
  targetType: instance
  targetGroupARN: "${STAGE9_ORDER_TG_ARN}"
---
apiVersion: elbv2.k8s.aws/v1beta1
kind: TargetGroupBinding
metadata:
  name: user-service-tgb
  namespace: shopsphere-stage9
spec:
  serviceRef:
    name: user-service
    port: 8083
  targetType: instance
  targetGroupARN: "${STAGE9_USER_TG_ARN}"
