apiVersion: v1
kind: Secret
metadata:
  name: shopsphere-db-credentials
  namespace: shopsphere-stage9
  labels:
    app.kubernetes.io/name: shopsphere
    stage: "stage-9"
type: Opaque
stringData:
  # Injected securely via Jenkins / AWS Secrets Manager / deployment pipeline
  DB_PASSWORD: "ShopSphereSecurePass2026!"
