apiVersion: v1
kind: ConfigMap
metadata:
  name: shopsphere-common-config
  namespace: shopsphere-stage9
  labels:
    app.kubernetes.io/name: shopsphere
    stage: "stage-9"
data:
  NODE_ENV: "production"
  AWS_REGION: "us-east-1"
  DB_PORT: "5432"
  DB_NAME: "${DB_NAME}"
  DB_USER: "${DB_USER}"
  DB_SSL: "true"
  REDIS_PORT: "6379"
  # In production, these are injected dynamically by Terraform / deploy script
  DB_HOST: "${DB_HOST}"
  REDIS_HOST: "${REDIS_HOST}"
  SQS_QUEUE_URL: "${SQS_QUEUE_URL}"
