server:
  port: 8085

spring:
  application:
    name: payment-service
  data:
    mongodb:
      host: ${MONGODB_HOST:localhost}
      port: 27017
      database: shopsphere_payments
      username: root
      password: root
      authentication-database: admin
    redis:
      host: ${REDIS_HOST:localhost}
      port: 6379

stripe:
  secret-key: ${STRIPE_SECRET_KEY:your_stripe_secret_key_here}

logging:
  level:
    com.shopsphere: DEBUG
    org.springframework: INFO
